import { ApiProperty } from "@nestjs/swagger";

/**
 * Dto used for returning access tokens for the client.
 * Actually the content must be of type `UserLoginTokenDto` since it's typings are the same and this is used for certificating the user is logged-in
 */
export class AccessTokenDto {
  @ApiProperty({ description: 'The token returned on successfully login', example: 'tokenvaluehere' })
  public readonly token: string;
  constructor(token: string) {
    this.token = token;
  }
}

/**
* Dto that represents the deserialized content from the token generated by `AccessTokenDto`
*/
export class AccessTokenPayloadDto {
  @ApiProperty({description: 'The username of the user'})
  public readonly username: string;
  @ApiProperty({description: 'The user id'})
  public readonly sub: number;
  public readonly iat: number;
  constructor(username: string, sub: number, iat: number) {
    this.username = username;
    this.sub = sub;
    this.iat = iat;
  }
}
