

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: caina
      POSTGRES_PASSWORD: 564827913
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
